In [ ]:
pip install tensorflow==2.1.0

     |████████████████████████████████| 421.8MB 19kB/s 
     |████████████████████████████████| 450kB 52.2MB/s 
     |████████████████████████████████| 3.9MB 52.3MB/s 
     |████████████████████████████████| 51kB 8.7MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7542 sha256=0947d083cd21f4a59b552c513061c09c363a7711ce7f3e7671c5601a745ce230
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully 

In [ ]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [1]:
from zipfile import ZipFile
file="/content/drive/My Drive/Dataset.zip"
with ZipFile(file,'r') as zip:
  zip.extractall()
  print("process finished")

process finished


In [2]:
from tensorflow.keras.applications.vgg16 import VGG16,preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img,img_to_array
from tensorflow.keras.layers import Dense,Flatten,Dropout
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import Model

In [ ]:
vgg=VGG16(input_shape=[224,224,3],weights='imagenet',include_top=False)

58892288/58889256 [==============================] - 2s 0us/step


In [10]:
train="Dataset/Train"
test="Dataset/Test"

In [ ]:
for layer in vgg.layers:
  layer.trainable=False

In [ ]:
x=Flatten()(vgg.output)
l1=Dense(120,activation='relu')(x)
out=Dense(2,activation='softmax')(l1)

In [ ]:
model=Model(inputs=vgg.input,outputs=out)

In [ ]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])


In [11]:
train_datagen=ImageDataGenerator(rescale=1./255,
                                 shear_range=0.2,
                                 zoom_range=0.2,
                                 horizontal_flip=True)

In [12]:
train_set=train_datagen.flow_from_directory(train,
                                            target_size=(224,224),
                                            batch_size=32,
                                            class_mode="categorical")

Found 416 images belonging to 2 classes.


In [13]:
test_datagen=ImageDataGenerator(rescale=1./255)
test_set=test_datagen.flow_from_directory(test,
                                          target_size=(224,224),
                                          batch_size=32,
                                          shuffle=False,
                                          class_mode="categorical")

Found 134 images belonging to 2 classes.


In [14]:
train_set.class_indices

{'Parasite': 0, 'Uninfected': 1}

In [ ]:
checkpoints=ModelCheckpoint("/content/drive/My Drive/maleria-model-{epoch}.h5",monitor='val_accuracy',verbose=1,save_best_only=True,model='Max')
callbacks_list=[checkpoints]

In [ ]:
history=model.fit(train_set,validation_data=test_set,epochs=50,steps_per_epoch=len(train_set),validation_steps=len(test_set),callbacks=callbacks_list)

  ...
    to  
  ['...']
  ...
    to  
  ['...']
Train for 13 steps, validate for 5 steps
Epoch 1/50
12/13 [==========================>...] - ETA: 1s - loss: 0.9485 - accuracy: 0.6380
Epoch 00001: val_accuracy improved from -inf to 0.55224, saving model to /content/drive/My Drive/maleria-model-1.h5
13/13 [==============================] - 16s 1s/step - loss: 0.9244 - accuracy: 0.6346 - val_loss: 0.7438 - val_accuracy: 0.5522
Epoch 2/50
12/13 [==========================>...] - ETA: 0s - loss: 0.4254 - accuracy: 0.8125
Epoch 00002: val_accuracy improved from 0.55224 to 0.72388, saving model to /content/drive/My Drive/maleria-model-2.h5
13/13 [==============================] - 6s 476ms/step - loss: 0.4235 - accuracy: 0.8101 - val_loss: 0.4161 - val_accuracy: 0.7239
Epoch 3/50
12/13 [==========================>...] - ETA: 0s - loss: 0.3375 - accuracy: 0.8594
Epoch 00003: val_accuracy improved from 0.72388 to 0.79104, saving model to /content/drive/My Drive/maleria-model-3.h5
13/13 [======

In [ ]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [15]:
from tensorflow.keras.models import load_model
import numpy as np
model1=load_model("maleria-model-43.h5")

In [ ]:
model1.evaluate_generator(train_set)

Instructions for updating:
Please use Model.evaluate, which supports generators.
  ...
    to  
  ['...']


In [59]:
model1.evaluate_generator(test_set)

[0.0912272110581398, 0.9701492786407471]

In [63]:
filenames=test_set.filenames
nb_samples=len(filenames)
nb_samples

134

In [64]:
pred=model1.predict_generator(test_set,nb_samples)
prediction=np.argmax(pred,1)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [65]:
test_set.classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int32)

In [66]:
from sklearn.metrics import confusion_matrix,classification_report

In [67]:
confusion_matrix(prediction,test_set.classes)

array([[87,  0],
       [ 4, 43]])

In [68]:
print(classification_report(prediction,test_set.classes))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        87
           1       1.00      0.91      0.96        47

    accuracy                           0.97       134
   macro avg       0.98      0.96      0.97       134
weighted avg       0.97      0.97      0.97       134



# Predict single image

In [ ]:
img=load_img("/content/Dataset/Test/Parasite/C39P4thinF_original_IMG_20150622_105554_cell_13.png",target_size=(224,224))
test_img=img_to_array(img)
test_img=test_img/255
test_img=np.expand_dims(test_img,0)
pred=model1.predict(test_img)
pred=np.argmax(pred,1)
pred

array([0])

# Predict whole image

In [40]:
import os
for i in os.listdir("/content/Dataset/Test/Parasite"):
    s=os.path.join("/content/Dataset/Test/Parasite",i)
    img=load_img(s,target_size=(224,224))
    test_img=img_to_array(img)
    test_img=test_img/255
    test_img=np.expand_dims(test_img,0)
    # test_img=preprocess_input(test_img)
    pred=model1.predict(test_img)
    pred=np.argmax(pred,1)
    print(pred)


[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
